name: CI Build and Push to Docker Hub

on:
  push:
    tags:
      - 'v*'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 取得原始碼
      uses: actions/checkout@v3

    - name: 安裝 .NET 7 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: 還原 NuGet 套件
      run: dotnet restore

    - name: 建置 .NET 專案
      run: dotnet build --configuration Release

    - name: 執行單元測試
      run: dotnet test --no-build --verbosity normal

    - name: 登入 Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 建立並推送映像檔
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/copyimage:${{ github.ref_name }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/copyimage:${{ github.ref_name }}
