name: CI Build and Release

on:
  push:
    tags:
      - 'v*'  # 例如 v1.0.0

jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
    - name: 取得原始碼
      uses: actions/checkout@v3

    - name: 安裝 .NET 7 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: 還原 NuGet 套件
      run: dotnet restore

    - name: 建置 .NET 專案
      run: dotnet build --configuration Release

    - name: 執行單元測試
      run: dotnet test --no-build --verbosity normal

    - name: 建立發布資料夾
      run: |
        dotnet publish -c Release -o publish/
        zip -r release.zip publish/

    - name: 登入 Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 建立並推送 Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/copyimage:${{ github.ref_name }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/copyimage:${{ github.ref_name }}

    - name: 發佈 Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        files: release.zip
